language: elixir
sudo: false
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.1
otp_release:
  - 21.3
  - 20.3
  - 19.3
matrix:
  exclude:
    - otp_release: 21.3
      elixir: 1.4.5
    - otp_release: 21.3
      elixir: 1.5.3
    - otp_release: 19.3
      elixir: 1.8.1
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
script: mix test
after_script:
  - mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
